window.RECIPES = [

  // ===== КЕЙСЫ 100 =====
  { title: "Кейс для патронов 100", path: "craft/cases/reload_case_100.html", icon: "images/case/case_reload.png" },

  { title: "Черный кейс 100", path: "craft/cases/case_black_100.html", icon: "images/case/case_black.png" },
  { title: "Синий кейс 100", path: "craft/cases/case_blue_100.html", icon: "images/case/case_blue.png" },
  { title: "Зелёный кейс 100", path: "craft/cases/case_green_100.html", icon: "images/case/case_green.png" },
  { title: "Голубой кейс 100", path: "craft/cases/case_lightblue_100.html", icon: "images/case/case_lightblue.png" },
  { title: "Оранжевый кейс 100", path: "craft/cases/case_orange_100.html", icon: "images/case/case_orange.png" },
  { title: "Розовый кейс 100", path: "craft/cases/case_pink_100.html", icon: "images/case/case_pink.png" },
  { title: "Фиолетовый кейс 100", path: "craft/cases/case_purple_100.html", icon: "images/case/case_purple.png" },
  { title: "Красный кейс 100", path: "craft/cases/case_red_100.html", icon: "images/case/case_red.png" },
  { title: "Белый кейс 100", path: "craft/cases/case_white_100.html", icon: "images/case/case_white.png" },
  { title: "Желтый кейс 100", path: "craft/cases/case_yellow_100.html", icon: "images/case/case_yellow.png" },

  // ===== КЕЙСЫ 250 =====
  { title: "Черный кейс 250", path: "craft/cases/case_black_250.html", icon: "images/case/case_black.png" },
  { title: "Синий кейс 250", path: "craft/cases/case_blue_250.html", icon: "images/case/case_blue.png" },
  { title: "Зелёный кейс 250", path: "craft/cases/case_green_250.html", icon: "images/case/case_green.png" },
  { title: "Голубой кейс 250", path: "craft/cases/case_lightblue_250.html", icon: "images/case/case_lightblue.png" },
  { title: "Оранжевый кейс 250", path: "craft/cases/case_orange_250.html", icon: "images/case/case_orange.png" },
  { title: "Розовый кейс 250", path: "craft/cases/case_pink_250.html", icon: "images/case/case_pink.png" },
  { title: "Фиолетовый кейс 250", path: "craft/cases/case_purple_250.html", icon: "images/case/case_purple.png" },
  { title: "Красный кейс 250", path: "craft/cases/case_red_250.html", icon: "images/case/case_red.png" },
  { title: "Белый кейс 250", path: "craft/cases/case_white_250.html", icon: "images/case/case_white.png" },
  { title: "Желтый кейс 250", path: "craft/cases/case_yellow_250.html", icon: "images/case/case_yellow.png" },

  // ===== КЕЙСЫ 500 =====
  { title: "Черный кейс 500", path: "craft/cases/case_black_500.html", icon: "images/case/case_black.png" },
  { title: "Синий кейс 500", path: "craft/cases/case_blue_500.html", icon: "images/case/case_blue.png" },
  { title: "Зелёный кейс 500", path: "craft/cases/case_green_500.html", icon: "images/case/case_green.png" },
  { title: "Голубой кейс 500", path: "craft/cases/case_lightblue_500.html", icon: "images/case/case_lightblue.png" },
  { title: "Оранжевый кейс 500", path: "craft/cases/case_orange_500.html", icon: "images/case/case_orange.png" },
  { title: "Розовый кейс 500", path: "craft/cases/case_pink_500.html", icon: "images/case/case_pink.png" },
  { title: "Фиолетовый кейс 500", path: "craft/cases/case_purple_500.html", icon: "images/case/case_purple.png" },
  { title: "Красный кейс 500", path: "craft/cases/case_red_500.html", icon: "images/case/case_red.png" },
  { title: "Белый кейс 500", path: "craft/cases/case_white_500.html", icon: "images/case/case_white.png" },
  { title: "Желтый кейс 500", path: "craft/cases/case_yellow_500.html", icon: "images/case/case_yellow.png" },

  // ===== ОРУЖЕЙНЫЕ =====
  { title: "Кейс для оружия 100", path: "craft/cases/case_weapon_100.html", icon: "images/case/weapon_case.png" },
  { title: "Кейс для оружия 250", path: "craft/cases/case_weapon_250.html", icon: "images/case/weapon_case.png" },
  { title: "Кейс для оружия 500", path: "craft/cases/case_weapon_500.html", icon: "images/case/weapon_case.png" },

  // ===== ИНСТРУМЕНТЫ =====
  { title: "Ящик для инструментов 2 уровня", path: "craft/cases/tool_box_2.html", icon: "images/case/toolbox.png" },
  { title: "Ящик для инструментов 3 уровня", path: "craft/cases/tool_box_3.html", icon: "images/case/toolbox.png" },
  { title: "Ящик для инструментов 4 уровня", path: "craft/cases/tool_box_4.html", icon: "images/case/toolbox.png" },
  { title: "Ящик для инструментов 5 уровня", path: "craft/cases/tool_box_5.html", icon: "images/case/toolbox.png" },

  // ===== ПЕРЕНОСКА ОРУЖИЯ =====
  { title: "Ящик для переноски оружия 2 уровня", path: "craft/cases/weapon_crate_2.html", icon: "images/case/weapon_case_2.png" },
  { title: "Ящик для переноски оружия 3 уровня", path: "craft/cases/weapon_crate_3.html", icon: "images/case/weapon_case_3.png" },
  { title: "Ящик для переноски оружия 4 уровня", path: "craft/cases/weapon_crate_4.html", icon: "images/case/weapon_case_4.png" },

  // ===== ИГРУШКИ =====
  { title: "Ящик для 8 игрушек", path: "craft/cases/toy_box_8.html", icon: "images/case/toy_box_2.png" },
  { title: "Ящик для 12 игрушек", path: "craft/cases/toy_box_12.html", icon: "images/case/toy_box_3.png" },
  { title: "Ящик для 16 игрушек", path: "craft/cases/toy_box_16.html", icon: "images/case/toy_box_4.png" },
  { title: "Ящик для 32 игрушек", path: "craft/cases/toy_box_32.html", icon: "images/case/toy_box_5.png" },
  { title: "Ящик для 64 игрушек", path: "craft/cases/toy_box_64.html", icon: "images/case/toy_box_6.png" },

  // ===== СПЕЦ =====
  { title: "Аукционный кейс 750", path: "craft/cases/auk_case_750.html", icon: "images/case/case_auk_1.png" },

  // ===== Танки =====
  { title: "Кейс танк КВ-1 500", path: "craft/cases/case_tank_2.html", icon: "images/case/case_tank_2.png" },
  { title: "Кейс танк БТ-7 500", path: "craft/cases/case_tank_3.html", icon: "images/case/case_tank_3.png" },
  { title: "Кейс танк СУ-76 500", path: "craft/cases/case_tank_4.html", icon: "images/case/case_tank_4.png" },
  { title: "Кейс танк Т-34-85 500", path: "craft/cases/case_tank_5.html", icon: "images/case/case_tank_5.png" },
  { title: "Кейс танк ИСУ-152 500", path: "craft/cases/case_tank_6.html", icon: "images/case/case_tank_6.png" },

  // ===== Ящики =====
  { title: "Деревянный ящик 100", path: "craft/crates/crate_100.html", icon: "images/crates/crate_1.png" },
  { title: "Деревянный ящик 200", path: "craft/crates/crate_200.html", icon: "images/crates/crate_1.png" },
  { title: "Деревянный ящик 300", path: "craft/crates/crate_300.html", icon: "images/crates/crate_1.png" },
  { title: "Деревянный ящик 400", path: "craft/crates/crate_400.html", icon: "images/crates/crate_1.png" },
  { title: "Деревянный ящик 500", path: "craft/crates/crate_500.html", icon: "images/crates/crate_1.png" },

  // ===== Сундуки =====
  { title: "Матросский сундук 100", path: "craft/crates/chest_100.html", icon: "images/crates/chest_1.png" },
  { title: "Матросский сундук 200", path: "craft/crates/chest_200.html", icon: "images/crates/chest_1.png" },
  { title: "Матросский сундук 300", path: "craft/crates/chest_300.html", icon: "images/crates/chest_1.png" },
  { title: "Матросский сундук 400", path: "craft/crates/chest_400.html", icon: "images/crates/chest_1.png" },
  { title: "Матросский сундук 500", path: "craft/crates/chest_500.html", icon: "images/crates/chest_1.png" },

  // ===== Бочки =====
  { title: "Бочка 100", path: "craft/crates/barrel_100.html", icon: "images/crates/barrel_1.png" },
  { title: "Бочка 200", path: "craft/crates/barrel_200.html", icon: "images/crates/barrel_1.png" },
  { title: "Бочка 300", path: "craft/crates/barrel_300.html", icon: "images/crates/barrel_1.png" },
  { title: "Бочка 400", path: "craft/crates/barrel_400.html", icon: "images/crates/barrel_1.png" },
  { title: "Бочка 500", path: "craft/crates/barrel_500.html", icon: "images/crates/barrel_1.png" },

  // ===== Предметы =====
  { title: "Улучшенная усиленная удочка", path: "craft/items/rod_v2.html", icon: "images/items/rod_yw.png" },
  { title: "Порох", path: "craft/items/gunpowder.html", icon: "images/items/gunpowder.png" },
  { title: "Бронепластина Immortal", path: "craft/items/armor_plate_immortal.html", icon: "images/items/armor_plate_immortal.png" },
  { title: "Ткань Immortal", path: "craft/items/cloth_immortal.html", icon: "images/items/cloth_immortal.png" },
  { title: "Набор деталей экзоскелета", path: "craft/items/exo_nabor.html", icon: "images/items/exo_parts_box.png" },
  { title: "Канистра 100л", path: "craft/items/canister_100.html", icon: "images/items/canister_100.png" },
  { title: "Карта телепорта на данж - Скалистый", path: "craft/items/card_skalisty.html", icon: "images/items/card_skalik.png" },
  { title: "Карта телепорта на данж - Лабиринт", path: "craft/items/card_labirint.html", icon: "images/items/cad_labirint.png" },
  { title: "Боевой противогаз на 4 часа", path: "craft/items/gasmask_4.html", icon: "images/items/yw_gasmask.png" },
  { title: "Боевой противогаз на 8 часов", path: "craft/items/gasmask_8.html", icon: "images/items/yw_gasmask.png" },
  { title: "Боевой противогаз на 24 часа", path: "craft/items/gasmask_24.html", icon: "images/items/yw_gasmask.png" },
  { title: "Противогаз из маски от сета на 2 часа", path: "craft/items/set_mask_2.html", icon: "images/items/mask.png" },
  { title: "Противогаз из маски от сета на 2 часа", path: "craft/items/set_mask_4.html", icon: "images/items/mask.png" },
  { title: "Противогаз из маски от сета на 8 часов", path: "craft/items/set_mask_8.html", icon: "images/items/mask.png" },
  { title: "Противогаз из маски от сета на 24 часа", path: "craft/items/set_mask_24.html", icon: "images/items/mask.png" },

  // ===== Ножи =====
  { title: "Нож Gerber", path: "craft/knife/gerber.html", icon: "images/knife/gerber_2.png" },
  { title: "Тактический нож", path: "craft/knife/tactical.html", icon: "images/knife/tactical_2.png" },
  { title: "Секира молния V2", path: "craft/knife/sekira.html", icon: "images/knife/stormbreaker.png" },
  { title: "Самурайская катана V2", path: "craft/knife/katana.html", icon: "images/knife/samurai_katana.png" },

  // ===== Оружие =====
  { title: "CSR50 Bloody", path: "craft/weapons/csr_bloody.html", icon: "images/weapons/bloody/bloody_csr50.png" },
  { title: "M1928A1 Dark", path: "craft/weapons/pp_dark_v2.html", icon: "images/weapons/dark/dark_pp_v2.png" },
  { title: "PPSH Dark", path: "craft/weapons/pp_dark_v3.html", icon: "images/weapons/dark/dark_pp_v3.png" },
  { title: "Scorpion Dark", path: "craft/weapons/pp_dark_v4.html", icon: "images/weapons/dark/dark_pp_v4.png" },
  { title: "SUB2000 Dark", path: "craft/weapons/pp_dark_v5.html", icon: "images/weapons/dark/dark_pp_v5.png" },
  { title: "SUB2000-S Dark", path: "craft/weapons/pp_dark_v6.html", icon: "images/weapons/dark/dark_pp_v6.png" },
  { title: "AK-12 Dark", path: "craft/weapons/ar_762_dark_v2.html", icon: "images/weapons/dark/dark_ar762_v2.png" },
  { title: "AK47 Dark", path: "craft/weapons/ar_762_dark_v3.html", icon: "images/weapons/dark/dark_ar762_v3.png" },
  { title: "AKALPHA Dark", path: "craft/weapons/ar_762_dark_v4.html", icon: "images/weapons/dark/dark_ar762_v4.png" },
  { title: "AK15 Dark", path: "craft/weapons/ar_762_dark_v5.html", icon: "images/weapons/dark/dark_ar762_v5.png" },
  { title: "AEK971 Dark", path: "craft/weapons/ar_762_dark_v6.html", icon: "images/weapons/dark/dark_ar762_v6.png" },
  { title: "TAR21 Dark", path: "craft/weapons/ar_556_dark_v2.html", icon: "images/weapons/dark/dark_ar556_v2.png" },
  { title: "AR15 Dark", path: "craft/weapons/ar_556_dark_v3.html", icon: "images/weapons/dark/dark_ar556_v3.png" },
  { title: "MCR Dark", path: "craft/weapons/ar_556_dark_v4.html", icon: "images/weapons/dark/dark_ar556_v4.png" },
  { title: "HK417 Dark", path: "craft/weapons/ar_556_dark_v5.html", icon: "images/weapons/dark/dark_ar556_v5.png" },
  { title: "SCAR Dark", path: "craft/weapons/ar_556_dark_v6.html", icon: "images/weapons/dark/dark_ar556_v6.png" },
  { title: "M249 Dark", path: "craft/weapons/hmg_dark_v2.html", icon: "images/weapons/dark/dark_hmg_v2.png" },
  { title: "PKP Dark", path: "craft/weapons/hmg_dark_v3.html", icon: "images/weapons/dark/dark_hmg_v3.png" },
  { title: "M60E3 Dark", path: "craft/weapons/hmg_dark_v4.html", icon: "images/weapons/dark/dark_hmg_v4.png" },
  { title: "HK21 Dark", path: "craft/weapons/hmg_dark_v5.html", icon: "images/weapons/dark/dark_hmg_v5.png" },
  { title: "Evolys Dark", path: "craft/weapons/hmg_dark_v6.html", icon: "images/weapons/dark/dark_hmg_v6.png" },
  { title: "Kivaari Dark", path: "craft/weapons/rifle_dark_v2.html", icon: "images/weapons/dark/dark_rifle_v2.png" },
  { title: "M110 Dark", path: "craft/weapons/rifle_dark_v3.html", icon: "images/weapons/dark/dark_rifle_v3.png" },
  { title: "RSASS Dark", path: "craft/weapons/rifle_dark_v4.html", icon: "images/weapons/dark/dark_rifle_v4.png" },
  { title: "VSSK Dark", path: "craft/weapons/rifle_dark_v5.html", icon: "images/weapons/dark/dark_rifle_v5.png" },
  { title: "M82A2 Dark", path: "craft/weapons/rifle_dark_v6.html", icon: "images/weapons/dark/dark_rifle_v6.png" },
  { title: "HK416 Gold V2", path: "craft/weapons/gold_hk416_v2.html", icon: "images/weapons/gold/gold_hk416.png" },
  { title: "HK416 Gold V3", path: "craft/weapons/gold_hk416_v3.html", icon: "images/weapons/gold/gold_hk416.png" },
  { title: "AKM Gold V2", path: "craft/weapons/gold_akm_v2.html", icon: "images/weapons/gold/gold_akm.png" },
  { title: "AKM Gold V3", path: "craft/weapons/gold_akm_v3.html", icon: "images/weapons/gold/gold_akm.png" },
  { title: "Автомат AR-15 Bloody V2", path: "craft/weapons/bloody_ar15.html", icon: "images/weapons/bloody/bloody_ar15.png" },
  { title: "Автомат Phantom AR-15 Bloody V2", path: "craft/weapons/bloody_ar15_phantom.html", icon: "images/weapons/bloody/bloody_phantom_ar15.png" },
  { title: "Автомат DBR Bloody V2", path: "craft/weapons/bloody_dbr.html", icon: "images/weapons/bloody/bloody_dbr.png" },
  { title: "Автомат SIGSAUER Bloody V2", path: "craft/weapons/bloody_sigsauer.html", icon: "images/weapons/bloody/bloody_sigsauer.png" },
  { title: "Пулемет PKP Bloody V2", path: "craft/weapons/bloody_pkp.html", icon: "images/weapons/bloody/bloody_pkp.png" },
  { title: "LDR-308 Bloody V2", path: "craft/weapons/bloody_ldr308.html", icon: "images/weapons/bloody/bloody_ldr.png" },

  // ===== Предметы =====
  { title: "Улучшенная усиленная удочка", path: "craft/items/rod_v2.html", icon: "images/items/rod_yw.png" },
  { title: "Порох", path: "craft/items/gunpowder.html", icon: "images/items/gunpowder.png" },
  { title: "Бронепластина Immortal", path: "craft/items/armor_plate_immortal.html", icon: "images/items/armor_plate_immortal.png" },
  { title: "Ткань Immortal", path: "craft/items/cloth_immortal.html", icon: "images/items/cloth_immortal.png" },
  { title: "Набор деталей экзоскелета", path: "craft/items/exo_nabor.html", icon: "images/items/exo_parts_box.png" },
  { title: "Канистра 100л", path: "craft/items/canister_100.html", icon: "images/items/canister_100.png" },
  { title: "Карта телепорта на данж - Скалистый", path: "craft/items/card_skalisty.html", icon: "images/items/card_skalik.png" },
  { title: "Карта телепорта на данж - Лабиринт", path: "craft/items/card_labirint.html", icon: "images/items/cad_labirint.png" },
  { title: "Боевой противогаз на 4 часа", path: "craft/items/gasmask_4.html", icon: "images/items/yw_gasmask.png" },
  { title: "Боевой противогаз на 8 часов", path: "craft/items/gasmask_8.html", icon: "images/items/yw_gasmask.png" },
  { title: "Боевой противогаз на 24 часа", path: "craft/items/gasmask_24.html", icon: "images/items/yw_gasmask.png" },
  { title: "Противогаз из маски от сета на 2 часа", path: "craft/items/set_mask_2.html", icon: "images/items/mask.png" },
  { title: "Противогаз из маски от сета на 4 часа", path: "craft/items/set_mask_4.html", icon: "images/items/mask.png" },
  { title: "Противогаз из маски от сета на 8 часов", path: "craft/items/set_mask_8.html", icon: "images/items/mask.png" },
  { title: "Противогаз из маски от сета на 24 часа", path: "craft/items/set_mask_24.html", icon: "images/items/mask.png" },

  // ===== Верстак =====
  { title: "Стандартный патрон 20мм", path: "craft/workbench/ammo_20mm_v1.html", icon: "images/weapons/20mm_ammo.png" },
  { title: "Улучшенный патрон 20мм", path: "craft/workbench/ammo_20mm_v2.html", icon: "images/weapons/20mm_ammo.png" },
  { title: "Патроны 7.92x57", path: "craft/workbench/ammo_792x57.html", icon: "images/weapons/ammo_792x57.png" },
  { title: "Kriss Vector Dark", path: "craft/workbench/pp_dark_v1.html", icon: "images/weapons/dark/dark_pp_v1.png" },
  { title: "MBR Dark", path: "craft/workbench/ar_556_dark_v1.html", icon: "images/weapons/dark/dark_ar556_v1.png" },
  { title: "VSK94 Dark", path: "craft/workbench/ar_762_dark_v1.html", icon: "images/weapons/dark/dark_ar762_v1.png" },
  { title: "PKM Dark", path: "craft/workbench/hmg_dark_v1.html", icon: "images/weapons/dark/dark_hmg_v1.png" },
  { title: "AS50 Dark", path: "craft/workbench/hmg_dark_v1.html", icon: "images/weapons/dark/dark_hmg_v1.png" },
  { title: "PKM Dark", path: "craft/workbench/rifle_dark_v1.html", icon: "images/weapons/dark/dark_rifle_v1.png" },
  { title: "Брикет Crystal Eclipse", path: "craft/workbench/coca_crystal.html", icon: "images/items/coca_brick_crystal.png" },
  { title: "Брикет Lunar Aura", path: "craft/workbench/coca_lunar.html", icon: "images/items/coca_brick_lunar.png" },
  { title: "Брикет Madness Rainbow", path: "craft/workbench/coca_madness.html", icon: "images/items/coca_brick_madness.png" },
  { title: "Брикет Nirvana Spark", path: "craft/workbench/coca_nirvana.html", icon: "images/items/coca_brick_nirvana.png" },
  { title: "Брикет Whirlwind Ecstasy", path: "craft/workbench/coca_whirlwind.html", icon: "images/items/coca_brick_whirwind.png" },

  // ===== Сеты =====
  { title: "Кейс с сетом Calisto Undead V2", path: "craft/sets/set_calisto.html", icon: "images/sets/setbox_calisto.png" },
  { title: "Кейс с сетом Crusher V2", path: "craft/sets/set_crusher.html", icon: "images/sets/setbox_crusher.png" },
  { title: "Кейс с сетом Fixer V2", path: "craft/sets/set_fixer.html", icon: "images/sets/setbox_fixer.png" },
  { title: "Кейс с сетом Ghost V2", path: "craft/sets/set_ghost.html", icon: "images/sets/setbox_ghost.png" },
  { title: "Кейс с сетом Kasrkin V2", path: "craft/sets/set_kasrkin.html", icon: "images/sets/setbox_kasrkin_black.png" },
  { title: "Кейс с сетом Monochrome V2", path: "craft/sets/set_monochrome.html", icon: "images/sets/setbox_monochrome_blue.png" },
  { title: "Кейс с сетом Roxxon V2", path: "craft/sets/set_roxxon.html", icon: "images/sets/roxxon_black.png" },
  { title: "Кейс с сетом Sentinel V2", path: "craft/sets/set_sentinel.html", icon: "images/sets/sentinel.png" },
  { title: "Кейс с сетом Street Warrior V2", path: "craft/sets/set_streetwarrior.html", icon: "images/sets/streetwarrior.png" },

  // ===== Одежда =====
  { title: "Невидимый бронежилет V2", path: "craft/clothing/vest_inviz_v2.html", icon: "images/clothing/vest_inviz_v2.png" },
  { title: "Невидимый бронежилет V3", path: "craft/clothing/vest_inviz_v3.html", icon: "images/clothing/vest_inviz_v3.png" },
  { title: "Невидимый бронежилет V4", path: "craft/clothing/vest_inviz_v4.html", icon: "images/clothing/vest_inviz_v4.png" },
  { title: "Невидимый бронежилет V5", path: "craft/clothing/vest_inviz_v5.html", icon: "images/clothing/vest_inviz_v5.png" },
  { title: "Невидимый рюкзак V2", path: "craft/clothing/backpack_inviz_v2.html", icon: "images/clothing/backpack_inviz_v2.png" },
  { title: "Невидимый рюкзак V3", path: "craft/clothing/backpack_inviz_v3.html", icon: "images/clothing/backpack_inviz_v3.png" },
  { title: "Невидимый рюкзак V4", path: "craft/clothing/backpack_inviz_v4.html", icon: "images/clothing/backpack_inviz_v4.png" },
  { title: "Невидимый рюкзак V5", path: "craft/clothing/backpack_inviz_v5.html", icon: "images/clothing/backpack_inviz_v5.png" },
  { title: "Невидимый ремешок для ПНВ V2", path: "craft/clothing/nvgstrap_inviz_v2.html", icon: "images/clothing/nvgstrap_inviz.png" },
  { title: "Невидимый ремень V2", path: "craft/clothing/belt_inviz_v2.html", icon: "images/clothing/belt_inviz.png" },
  { title: "Экзоскелет V1", path: "craft/clothing/exo_crusher_v1.html", icon: "images/clothing/crusher_exo.png" },
  { title: "Экзоскелет V2", path: "craft/clothing/exo_crusher_v2.html", icon: "images/clothing/crusher_exo.png" },
  { title: "Экзоскелет Black V1", path: "craft/clothing/exo_roxxon_black_v1.html", icon: "images/clothing/roxxon_exo_black.png" },
  { title: "Экзоскелет Black V2", path: "craft/clothing/exo_roxxon_black_v2.html", icon: "images/clothing/roxxon_exo_black.png" },
  { title: "Экзоскелет Red V1", path: "craft/clothing/exo_roxxon_red_v1.html", icon: "images/clothing/roxxon_exo_red.png" },
  { title: "Экзоскелет Red V2", path: "craft/clothing/exo_roxxon_red_v2.html", icon: "images/clothing/roxxon_exo_red.png" },
  { title: "Бронежилет Аль Катала V2", path: "craft/clothing/katala_vest_v2.html", icon: "images/clothing/katala_vest.png" },
  { title: "Куртка Аль Катала V2", path: "craft/clothing/katala_jacket_v2.html", icon: "images/clothing/katala_jacket.png" },
  { title: "Штаны Аль Катала V2", path: "craft/clothing/katala_pants_v2.html", icon: "images/clothing/katala_pants.png" },
  { title: "Капюшон Biohazard NBC", path: "craft/clothing/biohazard_hood_nbc.html", icon: "images/clothing/biohazard_hood.png" },
  { title: "Ремень Biohazard V2", path: "craft/clothing/biohazard_belt_v2.html", icon: "images/clothing/biohazard_belt.png" },
  { title: "Рюкзак Biohazard V2", path: "craft/clothing/biohazard_backpack_v2.html", icon: "images/clothing/biohazard_backpack.png" },
  { title: "Капюшон Biohazard V2", path: "craft/clothing/biohazard_hood_v2.html", icon: "images/clothing/biohazard_hood.png" },
  { title: "Капюшон Biohazard V3", path: "craft/clothing/biohazard_hood_v3.html", icon: "images/clothing/biohazard_hood.png" },
  { title: "Капюшон Biohazard V4", path: "craft/clothing/biohazard_hood_v4.html", icon: "images/clothing/biohazard_hood.png" },
  { title: "Капюшон Biohazard V5", path: "craft/clothing/biohazard_hood_v5.html", icon: "images/clothing/biohazard_hood.png" },
  { title: "Бронежилет Biohazard V2", path: "craft/clothing/biohazard_vest_v2.html", icon: "images/clothing/biohazard_vest.png" },
  { title: "Бронежилет Biohazard V3", path: "craft/clothing/biohazard_vest_v3.html", icon: "images/clothing/biohazard_vest.png" },
  { title: "Бронежилет Biohazard V4", path: "craft/clothing/biohazard_vest_v4.html", icon: "images/clothing/biohazard_vest.png" },
  { title: "Бронежилет Biohazard V5", path: "craft/clothing/biohazard_vest_v5.html", icon: "images/clothing/biohazard_vest.png" },
  { title: "Куртка Biohazard V2", path: "craft/clothing/biohazard_jacket_v2.html", icon: "images/clothing/biohazard_jacket.png" },
  { title: "Куртка Biohazard V3", path: "craft/clothing/biohazard_jacket_v3.html", icon: "images/clothing/biohazard_jacket.png" },
  { title: "Куртка Biohazard V4", path: "craft/clothing/biohazard_jacket_v4.html", icon: "images/clothing/biohazard_jacket.png" },
  { title: "Куртка Biohazard V5", path: "craft/clothing/biohazard_jacket_v5.html", icon: "images/clothing/biohazard_jacket.png" },
  { title: "Штаны Biohazard V2", path: "craft/clothing/biohazard_pants_v2.html", icon: "images/clothing/biohazard_pants.png" },
  { title: "Штаны Biohazard V3", path: "craft/clothing/biohazard_pants_v3.html", icon: "images/clothing/biohazard_pants.png" },
  { title: "Штаны Biohazard V4", path: "craft/clothing/biohazard_pants_v4.html", icon: "images/clothing/biohazard_pants.png" },
  { title: "Штаны Biohazard V5", path: "craft/clothing/biohazard_pants_v5.html", icon: "images/clothing/biohazard_pants.png" },
  { title: "Шлем CAJ NBC", path: "craft/clothing/caj_helmet_nbc.html", icon: "images/clothing/caj_helmet.png" },
  { title: "Перчатки CAJ NBC", path: "craft/clothing/caj_gloves_nbc.html", icon: "images/clothing/caj_gloves.png" },
  { title: "Ботинки CAJ NBC", path: "craft/clothing/caj_boots_nbc.html", icon: "images/clothing/caj_boots.png" },
  { title: "Ремень CAJ V2", path: "craft/clothing/caj_belt_v2.html", icon: "images/clothing/caj_belt.png" },
  { title: "Шлем CAJ V2", path: "craft/clothing/caj_helmet_v2.html", icon: "images/clothing/caj_helmet.png" },
  { title: "Шлем CAJ V3", path: "craft/clothing/caj_helmet_v3.html", icon: "images/clothing/caj_helmet.png" },
  { title: "Шлем CAJ V4", path: "craft/clothing/caj_helmet_v4.html", icon: "images/clothing/caj_helmet.png" },
  { title: "Шлем CAJ V5", path: "craft/clothing/caj_helmet_v5.html", icon: "images/clothing/caj_helmet.png" },
  { title: "Бронежилет CAJ V2", path: "craft/clothing/caj_vest_v2.html", icon: "images/clothing/caj_vest.png" },
  { title: "Бронежилет CAJ V3", path: "craft/clothing/caj_vest_v3.html", icon: "images/clothing/caj_vest.png" },
  { title: "Бронежилет CAJ V4", path: "craft/clothing/caj_vest_v4.html", icon: "images/clothing/caj_vest.png" },
  { title: "Бронежилет CAJ V5", path: "craft/clothing/caj_vest_v5.html", icon: "images/clothing/caj_vest.png" },
  { title: "Куртка CAJ V2", path: "craft/clothing/caj_jacket_v2.html", icon: "images/clothing/caj_jacket.png" },
  { title: "Куртка CAJ V3", path: "craft/clothing/caj_jacket_v3.html", icon: "images/clothing/caj_jacket.png" },
  { title: "Куртка CAJ V4", path: "craft/clothing/caj_jacket_v4.html", icon: "images/clothing/caj_jacket.png" },
  { title: "Куртка CAJ V5", path: "craft/clothing/caj_jacket_v5.html", icon: "images/clothing/caj_jacket.png" },
  { title: "Штаны CAJ V2", path: "craft/clothing/caj_pants_v2.html", icon: "images/clothing/caj_pants.png" },
  { title: "Штаны CAJ V3", path: "craft/clothing/caj_pants_v3.html", icon: "images/clothing/caj_pants.png" },
  { title: "Штаны CAJ V4", path: "craft/clothing/caj_pants_v4.html", icon: "images/clothing/caj_pants.png" },
  { title: "Штаны CAJ V5", path: "craft/clothing/caj_pants_v5.html", icon: "images/clothing/caj_pants.png" },
  { title: "Шлем Dead Agent NBC", path: "craft/clothing/deadagent_helmet_nbc.html", icon: "images/clothing/deadagent_helmet_green.png" },
  { title: "Перчатки Dead Agent NBC", path: "craft/clothing/deadagent_gloves_nbc.html", icon: "images/clothing/deadagent_gloves_green.png" },
  { title: "Ботинки Dead Agent NBC", path: "craft/clothing/deadagent_boots_nbc.html", icon: "images/clothing/deadagent_boots_green.png" },
  { title: "Шлем Dead Agent V2", path: "craft/clothing/deadagent_helmet_v2.html", icon: "images/clothing/deadagent_helmet_green.png" },
  { title: "Шлем Dead Agent V3", path: "craft/clothing/deadagent_helmet_v3.html", icon: "images/clothing/deadagent_helmet_green.png" },
  { title: "Шлем Dead Agent V4", path: "craft/clothing/deadagent_helmet_v4.html", icon: "images/clothing/deadagent_helmet_green.png" },
  { title: "Шлем Dead Agent V5", path: "craft/clothing/deadagent_helmet_v5.html", icon: "images/clothing/deadagent_helmet_green.png" },
  { title: "Куртка Dead Agent V2", path: "craft/clothing/deadagent_jacket_v2.html", icon: "images/clothing/deadagent_jacket_green.png" },
  { title: "Куртка Dead Agent V3", path: "craft/clothing/deadagent_jacket_v3.html", icon: "images/clothing/deadagent_jacket_green.png" },
  { title: "Куртка Dead Agent V4", path: "craft/clothing/deadagent_jacket_v4.html", icon: "images/clothing/deadagent_jacket_green.png" },
  { title: "Куртка Dead Agent V5", path: "craft/clothing/deadagent_jacket_v5.html", icon: "images/clothing/deadagent_jacket_green.png" },
  { title: "Штаны Dead Agent V2", path: "craft/clothing/deadagent_pants_v2.html", icon: "images/clothing/deadagent_pants_green.png" },
  { title: "Штаны Dead Agent V3", path: "craft/clothing/deadagent_pants_v3.html", icon: "images/clothing/deadagent_pants_green.png" },
  { title: "Штаны Dead Agent V4", path: "craft/clothing/deadagent_pants_v4.html", icon: "images/clothing/deadagent_pants_green.png" },
  { title: "Штаны Dead Agent V5", path: "craft/clothing/deadagent_pants_v5.html", icon: "images/clothing/deadagent_pants_green.png" },
  { title: "Шлем Rusher NBC", path: "craft/clothing/rusher_helmet_nbc.html", icon: "images/clothing/rusher_helmet.png" },
  { title: "Перчатки Rusher NBC", path: "craft/clothing/rusher_gloves_nbc.html", icon: "images/clothing/rusher_gloves.png" },
  { title: "Ботинки Rusher NBC", path: "craft/clothing/rusher_boots_nbc.html", icon: "images/clothing/rusher_boots.png" },
  { title: "Шлем Rusher V2", path: "craft/clothing/rusher_helmet_v2.html", icon: "images/clothing/rusher_helmet.png" },
  { title: "Шлем Rusher V3", path: "craft/clothing/rusher_helmet_v3.html", icon: "images/clothing/rusher_helmet.png" },
  { title: "Шлем Rusher V4", path: "craft/clothing/rusher_helmet_v4.html", icon: "images/clothing/rusher_helmet.png" },
  { title: "Шлем Rusher V5", path: "craft/clothing/rusher_helmet_v5.html", icon: "images/clothing/rusher_helmet.png" },
  { title: "Бронежилет Rusher V2", path: "craft/clothing/rusher_vest_v2.html", icon: "images/clothing/rusher_vest.png" },
  { title: "Бронежилет Rusher V3", path: "craft/clothing/rusher_vest_v3.html", icon: "images/clothing/rusher_vest.png" },
  { title: "Бронежилет Rusher V4", path: "craft/clothing/rusher_vest_v4.html", icon: "images/clothing/rusher_vest.png" },
  { title: "Бронежилет Rusher V5", path: "craft/clothing/rusher_vest_v5.html", icon: "images/clothing/rusher_vest.png" },
  { title: "Куртка Rusher V2", path: "craft/clothing/rusher_jacket_v2.html", icon: "images/clothing/rusher_jacket.png" },
  { title: "Куртка Rusher V3", path: "craft/clothing/rusher_jacket_v3.html", icon: "images/clothing/rusher_jacket.png" },
  { title: "Куртка Rusher V4", path: "craft/clothing/rusher_jacket_v4.html", icon: "images/clothing/rusher_jacket.png" },
  { title: "Куртка Rusher V5", path: "craft/clothing/rusher_jacket_v5.html", icon: "images/clothing/rusher_jacket.png" },
  { title: "Штаны Rusher V2", path: "craft/clothing/rusher_pants_v2.html", icon: "images/clothing/rusher_pants.png" },
  { title: "Штаны Rusher V3", path: "craft/clothing/rusher_pants_v3.html", icon: "images/clothing/rusher_pants.png" },
  { title: "Штаны Rusher V4", path: "craft/clothing/rusher_pants_v4.html", icon: "images/clothing/rusher_pants.png" },
  { title: "Штаны Rusher V5", path: "craft/clothing/rusher_pants_v5.html", icon: "images/clothing/rusher_pants.png" },
  { title: "Шлем Shepard NBC", path: "craft/clothing/shepard_helmet_nbc.html", icon: "images/clothing/shepard_helmet.png" },
  { title: "Перчатки Shepard NBC", path: "craft/clothing/shepard_gloves_nbc.html", icon: "images/clothing/shepard_gloves.png" },
  { title: "Ботинки Shepard NBC", path: "craft/clothing/shepard_boots_nbc.html", icon: "images/clothing/shepard_boots.png" },
  { title: "Шлем Shepard V2", path: "craft/clothing/shepard_helmet_v2.html", icon: "images/clothing/shepard_helmet.png" },
  { title: "Шлем Shepard V3", path: "craft/clothing/shepard_helmet_v3.html", icon: "images/clothing/shepard_helmet.png" },
  { title: "Шлем Shepard V4", path: "craft/clothing/shepard_helmet_v4.html", icon: "images/clothing/shepard_helmet.png" },
  { title: "Шлем Shepard V5", path: "craft/clothing/shepard_helmet_v5.html", icon: "images/clothing/shepard_helmet.png" },
  { title: "Куртка Shepard V2", path: "craft/clothing/shepard_jacket_v2.html", icon: "images/clothing/shepard_jacket.png" },
  { title: "Куртка Shepard V3", path: "craft/clothing/shepard_jacket_v3.html", icon: "images/clothing/shepard_jacket.png" },
  { title: "Куртка Shepard V4", path: "craft/clothing/shepard_jacket_v4.html", icon: "images/clothing/shepard_jacket.png" },
  { title: "Куртка Shepard V5", path: "craft/clothing/shepard_jacket_v5.html", icon: "images/clothing/shepard_jacket.png" },
  { title: "Штаны Shepard V2", path: "craft/clothing/shepard_pants_v2.html", icon: "images/clothing/shepard_pants.png" },
  { title: "Штаны Shepard V3", path: "craft/clothing/shepard_pants_v3.html", icon: "images/clothing/shepard_pants.png" },
  { title: "Штаны Shepard V4", path: "craft/clothing/shepard_pants_v4.html", icon: "images/clothing/shepard_pants.png" },
  { title: "Штаны Shepard V5", path: "craft/clothing/shepard_pants_v5.html", icon: "images/clothing/shepard_pants.png" },
  { title: "Шлем Thirst NBC", path: "craft/clothing/thirst_helmet_nbc.html", icon: "images/clothing/thirst_helmet.png" },
  { title: "Перчатки Thirst NBC", path: "craft/clothing/thirst_gloves_nbc.html", icon: "images/clothing/thirst_gloves.png" },
  { title: "Ботинки Thirst NBC", path: "craft/clothing/thirst_boots_nbc.html", icon: "images/clothing/thirst_boots.png" },
  { title: "Шлем Thirst V2", path: "craft/clothing/thirst_helmet_v2.html", icon: "images/clothing/thirst_helmet.png" },
  { title: "Шлем Thirst V3", path: "craft/clothing/thirst_helmet_v3.html", icon: "images/clothing/thirst_helmet.png" },
  { title: "Шлем Thirst V4", path: "craft/clothing/thirst_helmet_v4.html", icon: "images/clothing/thirst_helmet.png" },
  { title: "Шлем Thirst V5", path: "craft/clothing/thirst_helmet_v5.html", icon: "images/clothing/thirst_helmet.png" },
  { title: "Бронежилет Thirst V2", path: "craft/clothing/thirst_vest_v2.html", icon: "images/clothing/thirst_vest.png" },
  { title: "Бронежилет Thirst V3", path: "craft/clothing/thirst_vest_v3.html", icon: "images/clothing/thirst_vest.png" },
  { title: "Бронежилет Thirst V4", path: "craft/clothing/thirst_vest_v4.html", icon: "images/clothing/thirst_vest.png" },
  { title: "Бронежилет Thirst V5", path: "craft/clothing/thirst_vest_v5.html", icon: "images/clothing/thirst_vest.png" },
  { title: "Куртка Thirst V2", path: "craft/clothing/thirst_jacket_v2.html", icon: "images/clothing/thirst_jacket.png" },
  { title: "Куртка Thirst V3", path: "craft/clothing/thirst_jacket_v3.html", icon: "images/clothing/thirst_jacket.png" },
  { title: "Куртка Thirst V4", path: "craft/clothing/thirst_jacket_v4.html", icon: "images/clothing/thirst_jacket.png" },
  { title: "Куртка Thirst V5", path: "craft/clothing/thirst_jacket_v5.html", icon: "images/clothing/thirst_jacket.png" },
  { title: "Штаны Thirst V2", path: "craft/clothing/thirst_pants_v2.html", icon: "images/clothing/thirst_pants.png" },
  { title: "Штаны Thirst V3", path: "craft/clothing/thirst_pants_v3.html", icon: "images/clothing/thirst_pants.png" },
  { title: "Штаны Thirst V4", path: "craft/clothing/thirst_pants_v4.html", icon: "images/clothing/thirst_pants.png" },
  { title: "Штаны Thirst V5", path: "craft/clothing/thirst_pants_v5.html", icon: "images/clothing/thirst_pants.png" },
  { title: "Шлем Trooper NBC", path: "craft/clothing/trooper_helmet_nbc.html", icon: "images/clothing/trooper_helmet.png" },
  { title: "Перчатки Trooper NBC", path: "craft/clothing/trooper_gloves_nbc.html", icon: "images/clothing/trooper_gloves.png" },
  { title: "Ботинки Trooper NBC", path: "craft/clothing/trooper_boots_nbc.html", icon: "images/clothing/trooper_boots.png" },
  { title: "Шлем Trooper V2", path: "craft/clothing/trooper_helmet_v2.html", icon: "images/clothing/trooper_helmet.png" },
  { title: "Шлем Trooper V3", path: "craft/clothing/trooper_helmet_v3.html", icon: "images/clothing/trooper_helmet.png" },
  { title: "Шлем Trooper V4", path: "craft/clothing/trooper_helmet_v4.html", icon: "images/clothing/trooper_helmet.png" },
  { title: "Шлем Trooper V5", path: "craft/clothing/trooper_helmet_v5.html", icon: "images/clothing/trooper_helmet.png" },
  { title: "Куртка Trooper V2", path: "craft/clothing/trooper_jacket_v2.html", icon: "images/clothing/trooper_jacket.png" },
  { title: "Куртка Trooper V3", path: "craft/clothing/trooper_jacket_v3.html", icon: "images/clothing/trooper_jacket.png" },
  { title: "Куртка Trooper V4", path: "craft/clothing/trooper_jacket_v4.html", icon: "images/clothing/trooper_jacket.png" },
  { title: "Куртка Trooper V5", path: "craft/clothing/trooper_jacket_v5.html", icon: "images/clothing/trooper_jacket.png" },
  { title: "Штаны Trooper V2", path: "craft/clothing/trooper_pants_v2.html", icon: "images/clothing/trooper_pants.png" },
  { title: "Штаны Trooper V3", path: "craft/clothing/trooper_pants_v3.html", icon: "images/clothing/trooper_pants.png" },
  { title: "Штаны Trooper V4", path: "craft/clothing/trooper_pants_v4.html", icon: "images/clothing/trooper_pants.png" },
  { title: "Штаны Trooper V5", path: "craft/clothing/trooper_pants_v5.html", icon: "images/clothing/trooper_pants.png" },
  { title: "Шлем Warfighter NBC", path: "craft/clothing/warfighter_helmet_nbc.html", icon: "images/clothing/warfighter_helmet.png" },
  { title: "Перчатки Warfighter NBC", path: "craft/clothing/warfighter_gloves_nbc.html", icon: "images/clothing/warfighter_gloves.png" },
  { title: "Ботинки Warfighter NBC", path: "craft/clothing/warfighter_boots_nbc.html", icon: "images/clothing/warfighter_boots.png" },
  { title: "Ремень Warfighter V2", path: "craft/clothing/warfighter_belt_v2.html", icon: "images/clothing/warfighter_belt.png" },
  { title: "Шлем Warfighter V2", path: "craft/clothing/warfighter_helmet_v2.html", icon: "images/clothing/warfighter_helmet.png" },
  { title: "Шлем Warfighter V3", path: "craft/clothing/warfighter_helmet_v3.html", icon: "images/clothing/warfighter_helmet.png" },
  { title: "Шлем Warfighter V4", path: "craft/clothing/warfighter_helmet_v4.html", icon: "images/clothing/warfighter_helmet.png" },
  { title: "Шлем Warfighter V5", path: "craft/clothing/warfighter_helmet_v5.html", icon: "images/clothing/warfighter_helmet.png" },
  { title: "Бронежилет Warfighter V2", path: "craft/clothing/warfighter_vest_v2.html", icon: "images/clothing/warfighter_vest.png" },
  { title: "Бронежилет Warfighter V3", path: "craft/clothing/warfighter_vest_v3.html", icon: "images/clothing/warfighter_vest.png" },
  { title: "Бронежилет Warfighter V4", path: "craft/clothing/warfighter_vest_v4.html", icon: "images/clothing/warfighter_vest.png" },
  { title: "Бронежилет Warfighter V5", path: "craft/clothing/warfighter_vest_v5.html", icon: "images/clothing/warfighter_vest.png" },
  { title: "Куртка Warfighter V2", path: "craft/clothing/warfighter_jacket_v2.html", icon: "images/clothing/warfighter_jacket.png" },
  { title: "Куртка Warfighter V3", path: "craft/clothing/warfighter_jacket_v3.html", icon: "images/clothing/warfighter_jacket.png" },
  { title: "Куртка Warfighter V4", path: "craft/clothing/warfighter_jacket_v4.html", icon: "images/clothing/warfighter_jacket.png" },
  { title: "Куртка Warfighter V5", path: "craft/clothing/warfighter_jacket_v5.html", icon: "images/clothing/warfighter_jacket.png" },
  { title: "Штаны Warfighter V2", path: "craft/clothing/warfighter_pants_v2.html", icon: "images/clothing/warfighter_pants.png" },
  { title: "Штаны Warfighter V3", path: "craft/clothing/warfighter_pants_v3.html", icon: "images/clothing/warfighter_pants.png" },
  { title: "Штаны Warfighter V4", path: "craft/clothing/warfighter_pants_v4.html", icon: "images/clothing/warfighter_pants.png" },
  { title: "Штаны Warfighter V5", path: "craft/clothing/warfighter_pants_v5.html", icon: "images/clothing/warfighter_pants.png" },
  { title: "Шлем Whimsy NBC", path: "craft/clothing/whimsy_helmet_nbc.html", icon: "images/clothing/whimsy_helmet_pink.png" },
  { title: "Перчатки Whimsy NBC", path: "craft/clothing/whimsy_gloves_nbc.html", icon: "images/clothing/whimsy_gloves_pink.png" },
  { title: "Ботинки Whimsy NBC", path: "craft/clothing/whimsy_boots_nbc.html", icon: "images/clothing/whimsy_boots_pink.png" },
  { title: "Шлем Whimsy V2", path: "craft/clothing/whimsy_helmet_v2.html", icon: "images/clothing/whimsy_helmet_pink.png" },
  { title: "Шлем Whimsy V3", path: "craft/clothing/whimsy_helmet_v3.html", icon: "images/clothing/whimsy_helmet_pink.png" },
  { title: "Шлем Whimsy V4", path: "craft/clothing/whimsy_helmet_v4.html", icon: "images/clothing/whimsy_helmet_pink.png" },
  { title: "Шлем Whimsy V5", path: "craft/clothing/whimsy_helmet_v5.html", icon: "images/clothing/whimsy_helmet_pink.png" },
  { title: "Бронежилет Whimsy V2", path: "craft/clothing/whimsy_vest_v2.html", icon: "images/clothing/whimsy_vest_pink.png" },
  { title: "Бронежилет Whimsy V3", path: "craft/clothing/whimsy_vest_v3.html", icon: "images/clothing/whimsy_vest_pink.png" },
  { title: "Бронежилет Whimsy V4", path: "craft/clothing/whimsy_vest_v4.html", icon: "images/clothing/whimsy_vest_pink.png" },
  { title: "Бронежилет Whimsy V5", path: "craft/clothing/whimsy_vest_v5.html", icon: "images/clothing/whimsy_vest_pink.png" },
  { title: "Куртка Whimsy V2", path: "craft/clothing/whimsy_jacket_v2.html", icon: "images/clothing/whimsy_jacket_pink.png" },
  { title: "Куртка Whimsy V3", path: "craft/clothing/whimsy_jacket_v3.html", icon: "images/clothing/whimsy_jacket_pink.png" },
  { title: "Куртка Whimsy V4", path: "craft/clothing/whimsy_jacket_v4.html", icon: "images/clothing/whimsy_jacket_pink.png" },
  { title: "Куртка Whimsy V5", path: "craft/clothing/whimsy_jacket_v5.html", icon: "images/clothing/whimsy_jacket_pink.png" },
  { title: "Штаны Whimsy V2", path: "craft/clothing/whimsy_pants_v2.html", icon: "images/clothing/whimsy_pants_pink.png" },
  { title: "Штаны Whimsy V3", path: "craft/clothing/whimsy_pants_v3.html", icon: "images/clothing/whimsy_pants_pink.png" },
  { title: "Штаны Whimsy V4", path: "craft/clothing/whimsy_pants_v4.html", icon: "images/clothing/whimsy_pants_pink.png" },
  { title: "Штаны Whimsy V5", path: "craft/clothing/whimsy_pants_v5.html", icon: "images/clothing/whimsy_pants_pink.png" },

  // ===== Магазины Dark =====
  { title: "Магазин Kriss Vector Dark - 60 патронов", path: "craft/mag_dark/mag_pp_dark_v1_60.html", icon: "images/weapons/dark/dark_pp_v1_mag.png" },
  { title: "Магазин Kriss Vector Dark - 90 патронов", path: "craft/mag_dark/mag_pp_dark_v1_90.html", icon: "images/weapons/dark/dark_pp_v1_mag.png" },
  { title: "Магазин Kriss Vector Dark - 150 патронов", path: "craft/mag_dark/mag_pp_dark_v1_150.html", icon: "images/weapons/dark/dark_pp_v1_mag.png" },
  { title: "Магазин M1928A1 Dark - 60 патронов", path: "craft/mag_dark/mag_pp_dark_v2_60.html", icon: "images/weapons/dark/dark_pp_v1_mag.png" },
  { title: "Магазин M1928A1 Dark - 90 патронов", path: "craft/mag_dark/mag_pp_dark_v2_90.html", icon: "images/weapons/dark/dark_pp_v1_mag.png" },
  { title: "Магазин M1928A1 Dark - 150 патронов", path: "craft/mag_dark/mag_pp_dark_v2_150.html", icon: "images/weapons/dark/dark_pp_v1_mag.png" },

];